#-------------------------------
# General Site Settings

company: PortalSense
title: Realidad Virtual para Construcción
description: Digitalizamos tu proyecto de construcción con sistemas interactivos en realidad virtual tipo metaverso para que transmitas credibilidad y sorprendas a tus clientes al comprar la vivienda de sus sueños.
logo: icon/logo.png
email: info@portalsense.com
phone: +57 315 885 8022
phone-link: https://wa.me/573158858022  # Formato internacional sin simbolos
address: Carrera 21#64A-33 (Of. 1002).<br> Multiplaza El Cable. <br> Manizales, Colombia.
address-link: https://goo.gl/maps/8NjGaFEXAc5hG5Ah6

link-media-kit: '/mediakit'

menu:
- {name: Portafolio, link: '/portafolio'}
- {name: Blog, link: '/blog'}
- {name: Contacto, link: '/contacto'}
# - {name: Demo, link: '/demo'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: https://support.google.com/tagmanager/answer/6102821

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your Google Tag Manager.

google-analytics: G-S8VQCQ2TWW # G-PR6BSK9SBR

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  # hero-title: Traemos al presente las ciudades del futuro con realidad virtual (VR) y extendida (XR).
  hero-title: Hacemos tu nuevo proyecto de construcción más fácil de entender para tus clientes.


social:
- {icon: "ti-facebook", link: "https://www.facebook.com/portalsense.xr/"}
- {icon: "ti-instagram", link: "https://www.instagram.com/portalsense.xr/"}
- {icon: "ti-linkedin", link: "https://www.linkedin.com/company/portalsense/"}
- {icon: "ti-youtube", link: "https://youtube.com/@portalsense/"}
- {icon: "ti-twitter", link: "https://twitter.com/portalsenseXR/"}
- {icon: "ti-tumblr", link: "https://tiktok.com/@portalsense/"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Ayudamos a constructoras a vender sus nuevos proyectos con experiencias interactivas que mejoran la satisfacción de quienes compran sobre planos la vivienda de sus sueños.
  # En PortalSense digitalizamos tu proyecto de construcción con sistemas interactivos en realidad virtual (VR) tipo metaverso para que transmitas credibilidad y sorprendas a tus clientes al comprar la vivienda de sus sueños. <br><br>
  # ¡Revolucionamos la forma de diseñar y vender proyectos de construcción!<br>
  # Reemplazamos renders y videos de futuros proyectos con entornos virtuales que te permiten experimentar tu futuro hogar al más mínimo detalle, y caminar en las viviendas incluso antes de que se empiecen a construir.

blurb-btn-link: '/contacto'
blurb-btn-name: ¡Contáctanos!

# My Team Section

team-title: Equipo
team:

  - title : "Daniel Sanchez"
    image : "assets/images/team/2-diseno-ds.png"
    designation : "Arte 3D"

  - title : "Jaime Aristizabal"
    image : "assets/images/team/1-proyectos-ja.png"
    designation : "Operaciones"

  - title : "Luis Quintero"
    image : "assets/images/team/5-tecnologia-lq.png"
    designation : "Tecnología"

  - title : "Luz Sanchez"
    image : "assets/images/team/3-internacional-as.png"
    designation : "Internacional"

  - title : "Nicolás Rios"
    image : "assets/images/team/6-arte3D-nr.png"
    designation : "Artista 3D"
  
  - title : "Ana María Hincapié"
    image : "assets/images/team/7-admin-amh.png"
    designation : "Administrativa"

  - title : "Hernando Nieto"
    image : "assets/images/team/8-dev-hnj.png"
    designation : "Desarrollador VR"

  - title : "Manuel Tirado"
    image : "assets/images/team/4-mercadeo-mt.png"
    designation : "Mercadeo"



#-------------------------------
# Skills Section

# skills-title: Habilidades
# skills:
# - {name: Realidad Virt, color: '#fdb157', value: '90%'}
# - {name: Logo Design, color: '#9473e6', value: '60%'}
# - {name: After Effects, color: '#bdecf6', value: '80%'}
# - {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

# experience-title: Experiencia
# experience:
# - {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
# - {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
# - {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


# #-------------------------------
# # Education Section

# education-title: Education
# education:
# - {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
# - {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
# - {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
# - {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section
  # icons from Themify

services-title: ¿Qué hacemos?
services:

- {
    name: Promoción inmobiliaria,
    icon: ti-home, # ti-panel,
    description: 'Si estás interesado en comprar vivienda nueva, visita nuestra oficina 
                para vivir una experiencia inmersiva que te permiten experimentar tu futuro
                hogar al mínimo detalle, y caminar en las viviendas incluso antes de que 
                se empiecen a construir.',
    active: # Add true to select section
  }
- {
    name: VR Cities,
    icon: ti-eye, #ti-video-camera,
    description: 'Nuestra plataforma VR Cities revoluciona la forma de diseñar y vender 
                  viviendas nuevas. A través de realidad virtual y un metaverso personalizado
                  puedes ver, caminar y sentir los espacios a construir en tu ciudad en el futuro.',
    active: true # Add true to select section
  }
- {
    name: Servicio a constructoras,
    icon: ti-map-alt,
    description: 'Empresas constructoras nos pueden contactar para incluir sus 
                proyectos inmobiliarios en nuestro portafolio reemplazamos antiguos renders y videos 
                de futuros proyectos con entornos interactivos virtuales en un metaverso de ciudad.',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-title: Portafolio
portfolio-home-items:
  - image : "assets/images/portfolio/proyectos/amarello-vr-2.jpg"
    url: "/portafolio/2019-06-30-proyecto-cfcya-amarello"
  - image : "assets/images/portfolio/proyectos/valtierra-vr.jpg"
    url: "/portafolio/2019-08-30-proyecto-valtierra"
  - image : "assets/images/portfolio/eventos/2018-09-01-mallplaza.jpg"
    url: "/portafolio/2018-09-01-demo-mall-plaza"
  - image : "assets/images/portfolio/eventos/2018-11-15-feria-construccion2.jpg"
    url: "/portafolio/2018-11-15-feria-construccion-sena"

# Portfolio Page
portfolio-label:
- {
    title : "Realidad Virtual",   # Reservado para futuros proyectos con VR cities
    type : "VR"
  }
- {
    title : "Eventos",
    type : "Eventos"
  }
- {
    title : "Proyectos",
    type : "Proyectos"
  }

#-------------------------------
# Testimonials Section
# testimonials-title: Testimonios
# testimonial-items:

  # - name: "Jesica Gomez"
  #   image: "assets/images/testimonial/client-1.png"
  #   designation: "CEO, Funder"
  #   content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-habitat360.png"
    url: "https://www.instagram.com/torre360manizales/"
    
  - logo: "assets/images/clients-logo/client-gi.png"
    url: "https://gestoresinmobiliariosgi.com/"
    
  - logo: "assets/images/clients-logo/client-cal3.png"
    url: "https://linea3cableaereo.com/"
  
  - logo: "assets/images/clients-logo/client-cfc.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-valtierra.png"
    url: "#"

# #-------------------------------
# # Work Process Section

# work-process:
#   - title : "Research and Plan"
#     icon : "assets/images/icons/plan.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
#   - title : "Design and Develop"
#     icon : "assets/images/icons/design.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
#   - title : "Deliver"
#     icon : "assets/images/icons/print.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."



# #-------------------------------
# # Sponsors Section

sponsors-items:
  - logo: "assets/images/clients-logo/logo-fe.png"
    url: ""
    
  - logo: "assets/images/clients-logo/logo-pres.png"
    url: ""

  - logo: "assets/images/clients-logo/logo-fe.png"
    url: ""
    
  - logo: "assets/images/clients-logo/logo-pres.png"
    url: ""

  - logo: "assets/images/clients-logo/logo-fe.png"
    url: ""
    
  - logo: "assets/images/clients-logo/logo-pres.png"
    url: ""

  - logo: "assets/images/clients-logo/logo-fe.png"
    url: ""
    
  - logo: "assets/images/clients-logo/logo-pres.png"
    url: ""


#-------------------------------
# Contact Section

contact-title: Contacto
contact-email: info@portalsense.com
