#-------------------------------
# General Site Settings

title: PortalSense | Realidad Virtual
logo: icon/logo.png
email: info@portalsense.com
phone: +57 313 737 1561
address: Manizales, Colombia.

menu:
- {name: Portafolio, link: '/portafolio'}
- {name: Blog, link: '/blog'}
- {name: Contacto, link: '/contacto'}
# - {name: Acerca de, link: '/about.html'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: UA-175200229-1

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Experiencias en Realidad Virtual para Negocios, Industria y Salud.

social:
- {icon: "ti-facebook", link: "https://www.facebook.com/portalsense.xr/"}
- {icon: "ti-instagram", link: "https://www.instagram.com/portalsense.xr/"}
- {icon: "ti-linkedin", link: "https://www.linkedin.com/company/portalsense/"}
#- {icon: "ti-dribbble", link: "#"}
#- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  
  En PortalSense ofrecemos acceso a un <b> portafolio de nuevos proyectos inmobiliarios </b> en la ciudad a través de nuestra tecnología de <b>realidad virtual</b> y <b>metaversos</b> 😎. 
  Revolucionamos la forma de diseñar y vender viviendas nuevas!
  🚧🔨 Reemplazamos renders y videos de futuros proyectos con entornos virtuales que te permiten experimentar tu futuro hogar al más mínimo detalle, y caminar en las viviendas incluso antes de que se empiecen a construir. <br><br>
  🏠 Si estás <b>interesado en comprar vivienda nueva</b>, visita nuestra oficina para vivir una experiencia inmersiva con nuestro portafolio de proyectos disponibles. <br>
  👷‍♀️ <b>Empresas constructoras</b> nos pueden contactar para incluir sus proyectos inmobiliarios en nuestro portafolio.

blurb-btn-link: '/contacto'
blurb-btn-name: Click para contactarnos

# My Team Section
# team-title: Equipo
# team:
#   - title : "Luis Quintero"
#     image : "assets/images/team/member-1.png"
#     designation : "Coordinador de Desarrollo"
    
#   - title : "Jaime Aristizabal"
#     image : "assets/images/team/member-2.png"
#     designation : "Coordinador Administrativo"

#-------------------------------
# Skills Section

# skills-title: Habilidades
# skills:
# - {name: Realidad Virt, color: '#fdb157', value: '90%'}
# - {name: Logo Design, color: '#9473e6', value: '60%'}
# - {name: After Effects, color: '#bdecf6', value: '80%'}
# - {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

# experience-title: Experiencia
# experience:
# - {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
# - {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
# - {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


# #-------------------------------
# # Education Section

# education-title: Education
# education:
# - {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
# - {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
# - {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
# - {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section
  # icons from Themify

services-title: ¿Qué hacemos?
services:

- {
    name: Promoción inmobiliaria,
    icon: ti-home, # ti-panel,
    description: 'Si estás interesado en comprar vivienda nueva, visita nuestra oficina 
                para vivir una experiencia inmersiva que te permiten experimentar tu futuro
                hogar al mínimo detalle, y caminar en las viviendas incluso antes de que 
                se empiecen a construir.',
    active: # Add true to select section
  }
- {
    name: VR Cities,
    icon: ti-eye, #ti-video-camera,
    description: 'Nuestra plataforma VR Cities revoluciona la forma de diseñar y vender 
                  viviendas nuevas. A través de realidad virtual y un metaverso personalizado
                  puedes ver, caminar y sentir los espacios a construir en tu ciudad en el futuro.',
    active: true # Add true to select section
  }
- {
    name: Servicio a constructoras,
    icon: ti-map-alt,
    description: 'Empresas constructoras nos pueden contactar para incluir sus 
                proyectos inmobiliarios en nuestro portafolio reemplazamos antiguos renders y videos 
                de futuros proyectos con entornos interactivos virtuales en un metaverso de ciudad.',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-title: Portafolio
portfolio-home-items:
  - image : "assets/images/vr/vr-woman.png"
    url: "https://cfcya.co/conoce-mas-de-amarello-con-realidad-virtual/"
    
  - image : "assets/images/portfolio/amarello-vr-cfc.jpg"
    url: "/portafolio/2019-06-30-cfcya-amarello"
    
  - image : "assets/images/portfolio/valtierra-vr.jpg"
    url: "/portafolio/2019-08-30-valtierra"

  - image : "assets/images/portfolio/item-4.png"
    url: "#"

# Portfolio Page
portfolio-label:
- {
    title : "Realidad Virtual",
    type : "VR"
  }
- {
    title : "Metaverso",
    type : "metaverso"
  }
- {
    title : "Vivienda",
    type : "vivienda"
  }


portfolio-items:
  - image : "assets/images/vr/vr-woman.png"
    url: "https://cfcya.co/conoce-mas-de-amarello-con-realidad-virtual/"
    portfolio-type:
     - type: "VR"
     - type: "vivienda"
      
  - image : "assets/images/portfolio/amarello-vr-cfc.jpg"
    url: "/portafolio/2019-06-30-cfcya-amarello"
    portfolio-type:
      - type: "VR"
      - type: "vivienda"

  - image : "assets/images/portfolio/valtierra-vr.jpg"
    url: "/portafolio/2019-08-30-valtierra"
    portfolio-type:
      - type: "VR"
      - type: "vivienda"
      
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    portfolio-type:
      - type: "metaverso"


# #-------------------------------
# # Testimonials Section
# testimonials-title: Testimonios
# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation : "CEO, Funder"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-valtierra.png"
    url: "https://construoferta.co/constproyecto/28/show"
    
  - logo: "assets/images/clients-logo/client-cfc.png"
    url: "http://cfcya.co/"

#-------------------------------
# Contact Section

contact-title: Contacto
contact-email: info@portalsense.com

#-------------------------------
# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
